### ISSUE TITLE
All projects endpoint

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/search#10]
We need a second endpoint that exposes all the projects and allows pagination and sorting/filtering

* load the applications file and keep in memory different instances of the projects list sorted by
  * contributions count
  * contributions amount
  * ... check the other 2
* it receives a random number used as starting index in the list to allow "random" projects selection at each refresh of the projects page but keeping the same for pagination
* return projects based on a list of ids

**Comment by bard** [comment]
Continued in #17 #24 #25 #26 

@carlbarrdahl issues probably also address your questions, at least partly.

**Comment by carlbarrdahl** [comment]
> Continued in #17 #24 #25 #26
> 
> @carlbarrdahl issues probably also address your questions, at least partly.

Great! Added a comment
