### ISSUE TITLE
Fetch project applications based on a list of rounds

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/search#9]
Requirements:

We will temporarily continue to have static data but instead of fetching the projects json file directly we need to fetch projects that applied to a list of rounds, the ones from GG19.

Out of scope:

* having data that updates live during the rounds
* having live data from any other round not in GG19

Design sketch:

* select a list of round contract addresses
* for each round fetch the applications file (https://indexer-production.fly.dev/data/424/rounds/0x1488817b0137CA16F35D72A5F2A7c095c1Ec9166/applications.json)
* filter only accepted applications (`status: APPROVED`)
* verify that `application.metadata.metadata.project` already contains the same data we have in the original project file
* export the project data + other fields that we will use for filters and sorting
  *  id
  * projectId (which is the keccak256 of `chainId, projectRegistryAddress, projectNumber`)
  *  amountUSD
  * votes 
  * roundId
* merge the applications from all the rounds in one single file

**Comment by bard** [comment]
Continued in #18
